;; SPDX-License

;; ****************************
;; *** @author: Έnosis Tech	***
;; *** @file: graphics.inc	***
;; *** @date: 16/04/2025	***
;; ****************************

;; *********************************
;; *** Avoid file re-definitions ***
;; *********************************

IFNDEF __GRAPHICS_INC__
__GRAPHICS_INC__ equ 1

EXTERN		VIDEO_MODE_ZERO
EXTERN		VIDEO_MODE_ONE
EXTERN		VIDEO_MODE_TWO
EXTERN		VIDEO_MODE_THREE

ENDIF