;; SPDX-License: GPL-2

;; ****************************
;; *** @author Έnosis Tech  ***
;; *** @version 00.00.01    ***
;; ****************************

;; *********************************
;; *** Avoid file re-definitions ***
;; *********************************

ifndef __ALIASES_INC__
define __ALIASES_INC__

;; Aliases for pointers

fnp 	equ free_next_process

;; Allies for the size of things

PSIZE	equ $0015 
SSIZE	equ $0200

endif