;; SPDX-License: GPL-2

;; ********************************
;; **** @author: Έnosis Tech	***
;; **** @file: fcntl.inc		***
;; **** @date: 30/04/2025		***
;; ********************************

IFNDEF __FCNTL_INC__
__FCNTL_INC__ equ 1

defgroup {
	
	SEEK_CUR
	SEEK_END
	SEEKJ3ET
	S_IRGRP
	SJROTH
	S_IRUSR
	S_IRWXG
	SJRWXO
	SJRWXU
	S_ISBLK
	S_ISCHR
	S_ISDIR
	S_ISFIFO
	S_ISGID
	S_ISREG
	S_ISUID
	S_IWGRP
	S_IWOTH
	S_IWUSR
	S_IXGRP
	S_IXOTH
	S_IXUSR

}

ENDIF